//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTBL
    {
        public int USER_PK { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string ROLE_TYPE { get; set; }
        public string STATUS { get; set; }
    }
}
